import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Category } from './api/schemas/types'

import {ApolloClient, InMemoryCache, gql} from '@apollo/client'

interface Props {
  categories: Category[]
}

export default function Home({
   categories
  }: Props) {
    console.log(categories)
  return (
    <div className={styles.container}>
      <Head>
        <title>Lang cards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Lang cards
        </h1>
      </main>
    </div>
  )
}

export async function getStaticProps() {

  const client = new ApolloClient({
    uri: 'https://countries.trevorblades.com',
    cache: new InMemoryCache()
  })

  const {data} = await client.query({
    query: gql`
      query Countries {
        countries {
          code
          name
          emoji
        }
      }
    `
  })

  return {
    props: {
      categories: data.countries.slice(0, 4)
    },
  }
}