import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { gql, useQuery } from '@apollo/client'
import { initializeApollo } from 'apollo'

const Query = gql`
  query Query {
    getCategories {
      title {
        english
        romanian
      }
    }
  }
`

export default function Home() {

  const { data, loading } = useQuery(Query)

  if (loading) return <span>loading...</span>

  return (
    <div className={styles.container}>
      <Head>
        <title>Lang cards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Lang cards
        </h1>
      </main>

      <pre>
        {JSON.stringify(data, null, 2)}
      </pre>
    </div>
  )
}

export async function getStaticProps() {

  const apolloClient = initializeApollo();

  await apolloClient.query({
    query: Query,
  });

  return {
    props: {
      initialApolloState: apolloClient.cache.extract(),
    },
  }
}